{
  "name": "CreditRiskAnalytics",
  "compatibilityLevel": 1567,
  "model": {
    "culture": "en-US",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "tables": [
      {
        "name": "dim_customer",
        "columns": [
          { "name": "customer_id", "dataType": "string", "sourceColumn": "customer_id" },
          { "name": "customer_name", "dataType": "string", "sourceColumn": "customer_name" },
          { "name": "age", "dataType": "int64", "sourceColumn": "age" },
          { "name": "monthly_income", "dataType": "double", "sourceColumn": "monthly_income" },
          { "name": "credit_score", "dataType": "int64", "sourceColumn": "credit_score" },
          { "name": "credit_score_band", "dataType": "string", "sourceColumn": "credit_score_band" },
          { "name": "employment_type", "dataType": "string", "sourceColumn": "employment_type" },
          { "name": "region", "dataType": "string", "sourceColumn": "region" }
        ],
        "partitions": [
          {
            "name": "dim_customer_Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    CsvFile = File.Contents(\"C:/Users/Ary Palacios/Desktop/credit-risk-loan-analytics/data/dim_customer.csv\"),",
                "    TableData = Csv.Document(CsvFile, [Delimiter=\",\", Columns=8, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    Headers = Table.PromoteHeaders(TableData, [PromoteAllScalars=true]),",
                "    Typed = Table.TransformColumnTypes(Headers, {{\"customer_id\", type text}, {\"customer_name\", type text}, {\"age\", Int64.Type}, {\"monthly_income\", type number}, {\"credit_score\", Int64.Type}, {\"credit_score_band\", type text}, {\"employment_type\", type text}, {\"region\", type text}})",
                "in",
                "    Typed"
              ]
            }
          }
        ]
      },
      {
        "name": "dim_date",
        "columns": [
          { "name": "date_id", "dataType": "string", "sourceColumn": "date_id" },
          { "name": "full_date", "dataType": "dateTime", "sourceColumn": "full_date" },
          { "name": "year_num", "dataType": "int64", "sourceColumn": "year_num" },
          { "name": "quarter_num", "dataType": "int64", "sourceColumn": "quarter_num" },
          { "name": "month_num", "dataType": "int64", "sourceColumn": "month_num" },
          { "name": "month_name", "dataType": "string", "sourceColumn": "month_name" },
          { "name": "year_month", "dataType": "string", "sourceColumn": "year_month" },
          { "name": "is_month_end", "dataType": "boolean", "sourceColumn": "is_month_end" }
        ],
        "partitions": [
          {
            "name": "dim_date_Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    CsvFile = File.Contents(\"C:/Users/Ary Palacios/Desktop/credit-risk-loan-analytics/data/dim_date.csv\"),",
                "    TableData = Csv.Document(CsvFile, [Delimiter=\",\", Columns=8, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    Headers = Table.PromoteHeaders(TableData, [PromoteAllScalars=true]),",
                "    Typed = Table.TransformColumnTypes(Headers, {{\"date_id\", type text}, {\"full_date\", type datetime}, {\"year_num\", Int64.Type}, {\"quarter_num\", Int64.Type}, {\"month_num\", Int64.Type}, {\"month_name\", type text}, {\"year_month\", type text}, {\"is_month_end\", type logical}})",
                "in",
                "    Typed"
              ]
            }
          }
        ]
      },
      {
        "name": "dim_loan",
        "columns": [
          { "name": "loan_id", "dataType": "string", "sourceColumn": "loan_id" },
          { "name": "customer_id", "dataType": "string", "sourceColumn": "customer_id" },
          { "name": "product_id", "dataType": "string", "sourceColumn": "product_id" },
          { "name": "origination_date", "dataType": "dateTime", "sourceColumn": "origination_date" },
          { "name": "origination_year_month", "dataType": "string", "sourceColumn": "origination_year_month" },
          { "name": "original_principal", "dataType": "double", "sourceColumn": "original_principal" },
          { "name": "annual_interest_rate", "dataType": "double", "sourceColumn": "annual_interest_rate" },
          { "name": "term_months", "dataType": "int64", "sourceColumn": "term_months" },
          { "name": "monthly_installment", "dataType": "double", "sourceColumn": "monthly_installment" },
          { "name": "initial_credit_score", "dataType": "int64", "sourceColumn": "initial_credit_score" },
          { "name": "initial_risk_grade", "dataType": "string", "sourceColumn": "initial_risk_grade" }
        ],
        "partitions": [
          {
            "name": "dim_loan_Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    CsvFile = File.Contents(\"C:/Users/Ary Palacios/Desktop/credit-risk-loan-analytics/data/dim_loan.csv\"),",
                "    TableData = Csv.Document(CsvFile, [Delimiter=\",\", Columns=11, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    Headers = Table.PromoteHeaders(TableData, [PromoteAllScalars=true]),",
                "    Typed = Table.TransformColumnTypes(Headers, {{\"loan_id\", type text}, {\"customer_id\", type text}, {\"product_id\", type text}, {\"origination_date\", type datetime}, {\"origination_year_month\", type text}, {\"original_principal\", type number}, {\"annual_interest_rate\", type number}, {\"term_months\", Int64.Type}, {\"monthly_installment\", type number}, {\"initial_credit_score\", Int64.Type}, {\"initial_risk_grade\", type text}})",
                "in",
                "    Typed"
              ]
            }
          }
        ]
      },
      {
        "name": "dim_product",
        "columns": [
          { "name": "product_id", "dataType": "string", "sourceColumn": "product_id" },
          { "name": "product_name", "dataType": "string", "sourceColumn": "product_name" },
          { "name": "product_category", "dataType": "string", "sourceColumn": "product_category" },
          { "name": "collateral_type", "dataType": "string", "sourceColumn": "collateral_type" },
          { "name": "min_term_months", "dataType": "int64", "sourceColumn": "min_term_months" },
          { "name": "max_term_months", "dataType": "int64", "sourceColumn": "max_term_months" },
          { "name": "base_annual_rate", "dataType": "double", "sourceColumn": "base_annual_rate" }
        ],
        "partitions": [
          {
            "name": "dim_product_Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    CsvFile = File.Contents(\"C:/Users/Ary Palacios/Desktop/credit-risk-loan-analytics/data/dim_product.csv\"),",
                "    TableData = Csv.Document(CsvFile, [Delimiter=\",\", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    Headers = Table.PromoteHeaders(TableData, [PromoteAllScalars=true]),",
                "    Typed = Table.TransformColumnTypes(Headers, {{\"product_id\", type text}, {\"product_name\", type text}, {\"product_category\", type text}, {\"collateral_type\", type text}, {\"min_term_months\", Int64.Type}, {\"max_term_months\", Int64.Type}, {\"base_annual_rate\", type number}})",
                "in",
                "    Typed"
              ]
            }
          }
        ]
      },
      {
        "name": "fct_daily_repayment",
        "columns": [
          { "name": "repayment_id", "dataType": "string", "sourceColumn": "repayment_id" },
          { "name": "payment_date_id", "dataType": "string", "sourceColumn": "payment_date_id" },
          { "name": "payment_date", "dataType": "dateTime", "sourceColumn": "payment_date" },
          { "name": "loan_id", "dataType": "string", "sourceColumn": "loan_id" },
          { "name": "principal_paid", "dataType": "double", "sourceColumn": "principal_paid" },
          { "name": "interest_paid", "dataType": "double", "sourceColumn": "interest_paid" },
          { "name": "fees_paid", "dataType": "double", "sourceColumn": "fees_paid" },
          { "name": "total_paid", "dataType": "double", "sourceColumn": "total_paid" },
          { "name": "days_past_due_at_payment", "dataType": "int64", "sourceColumn": "days_past_due_at_payment" }
        ],
        "partitions": [
          {
            "name": "fct_daily_repayment_Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    CsvFile = File.Contents(\"C:/Users/Ary Palacios/Desktop/credit-risk-loan-analytics/data/fct_daily_repayment.csv\"),",
                "    TableData = Csv.Document(CsvFile, [Delimiter=\",\", Columns=9, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    Headers = Table.PromoteHeaders(TableData, [PromoteAllScalars=true]),",
                "    Typed = Table.TransformColumnTypes(Headers, {{\"repayment_id\", type text}, {\"payment_date_id\", type text}, {\"payment_date\", type datetime}, {\"loan_id\", type text}, {\"principal_paid\", type number}, {\"interest_paid\", type number}, {\"fees_paid\", type number}, {\"total_paid\", type number}, {\"days_past_due_at_payment\", Int64.Type}})",
                "in",
                "    Typed"
              ]
            }
          }
        ]
      },
      {
        "name": "fct_loan_monthly_snapshot",
        "columns": [
          { "name": "snapshot_id", "dataType": "string", "sourceColumn": "snapshot_id" },
          { "name": "snapshot_date_id", "dataType": "string", "sourceColumn": "snapshot_date_id" },
          { "name": "snapshot_date", "dataType": "dateTime", "sourceColumn": "snapshot_date" },
          { "name": "loan_id", "dataType": "string", "sourceColumn": "loan_id" },
          { "name": "customer_id", "dataType": "string", "sourceColumn": "customer_id" },
          { "name": "product_id", "dataType": "string", "sourceColumn": "product_id" },
          { "name": "months_on_books", "dataType": "int64", "sourceColumn": "months_on_books" },
          { "name": "outstanding_principal", "dataType": "double", "sourceColumn": "outstanding_principal" },
          { "name": "accrued_interest", "dataType": "double", "sourceColumn": "accrued_interest" },
          { "name": "days_past_due", "dataType": "int64", "sourceColumn": "days_past_due" },
          { "name": "delinquency_bucket", "dataType": "string", "sourceColumn": "delinquency_bucket" },
          { "name": "is_par30", "dataType": "int64", "sourceColumn": "is_par30" },
          { "name": "is_par60", "dataType": "int64", "sourceColumn": "is_par60" },
          { "name": "is_par90", "dataType": "int64", "sourceColumn": "is_par90" },
          { "name": "is_npl", "dataType": "int64", "sourceColumn": "is_npl" },
          { "name": "loan_status", "dataType": "string", "sourceColumn": "loan_status" }
        ],
        "measures": [
          {
            "name": "Total Outstanding Balance",
            "expression": "SUM(fct_loan_monthly_snapshot[outstanding_principal])",
            "formatString": "$#,##0.00"
          },
          {
            "name": "PAR 30 Balance",
            "expression": "CALCULATE(SUM(fct_loan_monthly_snapshot[outstanding_principal]), fct_loan_monthly_snapshot[is_par30] = 1)",
            "formatString": "$#,##0.00"
          },
          {
            "name": "PAR 30 Ratio",
            "expression": "DIVIDE([PAR 30 Balance], [Total Outstanding Balance], 0)",
            "formatString": "0.00%"
          },
          {
            "name": "PAR 60 Balance",
            "expression": "CALCULATE(SUM(fct_loan_monthly_snapshot[outstanding_principal]), fct_loan_monthly_snapshot[is_par60] = 1)",
            "formatString": "$#,##0.00"
          },
          {
            "name": "PAR 60 Ratio",
            "expression": "DIVIDE([PAR 60 Balance], [Total Outstanding Balance], 0)",
            "formatString": "0.00%"
          },
          {
            "name": "PAR 90 Balance",
            "expression": "CALCULATE(SUM(fct_loan_monthly_snapshot[outstanding_principal]), fct_loan_monthly_snapshot[is_par90] = 1)",
            "formatString": "$#,##0.00"
          },
          {
            "name": "PAR 90 Ratio",
            "expression": "DIVIDE([PAR 90 Balance], [Total Outstanding Balance], 0)",
            "formatString": "0.00%"
          },
          {
            "name": "NPL Balance",
            "expression": "CALCULATE(SUM(fct_loan_monthly_snapshot[outstanding_principal]), fct_loan_monthly_snapshot[is_npl] = 1)",
            "formatString": "$#,##0.00"
          },
          {
            "name": "NPL Ratio",
            "expression": "DIVIDE([NPL Balance], [Total Outstanding Balance], 0)",
            "formatString": "0.00%"
          }
        ],
        "partitions": [
          {
            "name": "fct_loan_monthly_snapshot_Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    CsvFile = File.Contents(\"C:/Users/Ary Palacios/Desktop/credit-risk-loan-analytics/data/fct_loan_monthly_snapshot.csv\"),",
                "    TableData = Csv.Document(CsvFile, [Delimiter=\",\", Columns=16, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    Headers = Table.PromoteHeaders(TableData, [PromoteAllScalars=true]),",
                "    Typed = Table.TransformColumnTypes(Headers, {{\"snapshot_id\", type text}, {\"snapshot_date_id\", type text}, {\"snapshot_date\", type datetime}, {\"loan_id\", type text}, {\"customer_id\", type text}, {\"product_id\", type text}, {\"months_on_books\", Int64.Type}, {\"outstanding_principal\", type number}, {\"accrued_interest\", type number}, {\"days_past_due\", Int64.Type}, {\"delinquency_bucket\", type text}, {\"is_par30\", Int64.Type}, {\"is_par60\", Int64.Type}, {\"is_par90\", Int64.Type}, {\"is_npl\", Int64.Type}, {\"loan_status\", type text}})",
                "in",
                "    Typed"
              ]
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "fct_snapshot_to_date",
        "fromTable": "fct_loan_monthly_snapshot",
        "fromColumn": "snapshot_date_id",
        "toTable": "dim_date",
        "toColumn": "date_id"
      },
      {
        "name": "fct_snapshot_to_customer",
        "fromTable": "fct_loan_monthly_snapshot",
        "fromColumn": "customer_id",
        "toTable": "dim_customer",
        "toColumn": "customer_id"
      },
      {
        "name": "fct_snapshot_to_product",
        "fromTable": "fct_loan_monthly_snapshot",
        "fromColumn": "product_id",
        "toTable": "dim_product",
        "toColumn": "product_id"
      },
      {
        "name": "fct_snapshot_to_loan",
        "fromTable": "fct_loan_monthly_snapshot",
        "fromColumn": "loan_id",
        "toTable": "dim_loan",
        "toColumn": "loan_id"
      },
      {
        "name": "fct_repayment_to_loan",
        "fromTable": "fct_daily_repayment",
        "fromColumn": "loan_id",
        "toTable": "dim_loan",
        "toColumn": "loan_id"
      },
      {
        "name": "fct_repayment_to_date",
        "fromTable": "fct_daily_repayment",
        "fromColumn": "payment_date_id",
        "toTable": "dim_date",
        "toColumn": "date_id"
      }
    ]
  }
}