{
  "name": "CreditRiskAnalytics",
  "compatibilityLevel": 1567,
  "model": {
    "culture": "en-US",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "tables": [
      {
        "name": "dim_customer",
        "columns": [
          { "name": "customer_key", "dataType": "int64", "sourceColumn": "customer_key" },
          { "name": "customer_id", "dataType": "string", "sourceColumn": "customer_id" },
          { "name": "credit_score", "dataType": "int64", "sourceColumn": "credit_score" },
          { "name": "risk_rating", "dataType": "string", "sourceColumn": "risk_rating" },
          { "name": "annual_income", "dataType": "double", "sourceColumn": "annual_income" },
          { "name": "employment_status", "dataType": "string", "sourceColumn": "employment_status" },
          { "name": "geographic_region", "dataType": "string", "sourceColumn": "geographic_region" }
        ],
        "partitions": [
          {
            "name": "dim_customer",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"data/dim_customer.csv\"), [Delimiter=\",\", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"customer_key\", Int64.Type}, {\"customer_id\", type text}, {\"credit_score\", Int64.Type}, {\"risk_rating\", type text}, {\"annual_income\", type number}, {\"employment_status\", type text}, {\"geographic_region\", type text}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ]
      },
      {
        "name": "dim_date",
        "columns": [
          { "name": "date_key", "dataType": "int64", "sourceColumn": "date_key" },
          { "name": "date", "dataType": "dateTime", "sourceColumn": "date" },
          { "name": "year", "dataType": "int64", "sourceColumn": "year" },
          { "name": "quarter", "dataType": "int64", "sourceColumn": "quarter" },
          { "name": "month", "dataType": "int64", "sourceColumn": "month" },
          { "name": "month_name", "dataType": "string", "sourceColumn": "month_name" },
          { "name": "day", "dataType": "int64", "sourceColumn": "day" },
          { "name": "day_of_week", "dataType": "string", "sourceColumn": "day_of_week" }
        ],
        "partitions": [
          {
            "name": "dim_date",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"data/dim_date.csv\"), [Delimiter=\",\", Columns=8, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"date_key\", Int64.Type}, {\"date\", type date}, {\"year\", Int64.Type}, {\"quarter\", Int64.Type}, {\"month\", Int64.Type}, {\"month_name\", type text}, {\"day\", Int64.Type}, {\"day_of_week\", type text}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ]
      },
      {
        "name": "dim_loan",
        "columns": [
          { "name": "loan_key", "dataType": "int64", "sourceColumn": "loan_key" },
          { "name": "loan_id", "dataType": "string", "sourceColumn": "loan_id" },
          { "name": "customer_key", "dataType": "int64", "sourceColumn": "customer_key" },
          { "name": "product_key", "dataType": "int64", "sourceColumn": "product_key" },
          { "name": "disbursement_date_key", "dataType": "int64", "sourceColumn": "disbursement_date_key" },
          { "name": "maturity_date_key", "dataType": "int64", "sourceColumn": "maturity_date_key" },
          { "name": "original_principal", "dataType": "double", "sourceColumn": "original_principal" },
          { "name": "interest_rate", "dataType": "double", "sourceColumn": "interest_rate" },
          { "name": "term_months", "dataType": "int64", "sourceColumn": "term_months" },
          { "name": "loan_status", "dataType": "string", "sourceColumn": "loan_status" }
        ],
        "partitions": [
          {
            "name": "dim_loan",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"data/dim_loan.csv\"), [Delimiter=\",\", Columns=10, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"loan_key\", Int64.Type}, {\"loan_id\", type text}, {\"customer_key\", Int64.Type}, {\"product_key\", Int64.Type}, {\"disbursement_date_key\", Int64.Type}, {\"maturity_date_key\", Int64.Type}, {\"original_principal\", type number}, {\"interest_rate\", type number}, {\"term_months\", Int64.Type}, {\"loan_status\", type text}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ]
      },
      {
        "name": "dim_product",
        "columns": [
          { "name": "product_key", "dataType": "int64", "sourceColumn": "product_key" },
          { "name": "product_id", "dataType": "string", "sourceColumn": "product_id" },
          { "name": "product_name", "dataType": "string", "sourceColumn": "product_name" },
          { "name": "product_type", "dataType": "string", "sourceColumn": "product_type" },
          { "name": "collateral_type", "dataType": "string", "sourceColumn": "collateral_type" }
        ],
        "partitions": [
          {
            "name": "dim_product",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"data/dim_product.csv\"), [Delimiter=\",\", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"product_key\", Int64.Type}, {\"product_id\", type text}, {\"product_name\", type text}, {\"product_type\", type text}, {\"collateral_type\", type text}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ]
      },
      {
        "name": "fct_daily_repayment",
        "columns": [
          { "name": "repayment_key", "dataType": "int64", "sourceColumn": "repayment_key" },
          { "name": "loan_key", "dataType": "int64", "sourceColumn": "loan_key" },
          { "name": "payment_date_key", "dataType": "int64", "sourceColumn": "payment_date_key" },
          { "name": "principal_paid", "dataType": "double", "sourceColumn": "principal_paid" },
          { "name": "interest_paid", "dataType": "double", "sourceColumn": "interest_paid" },
          { "name": "fee_paid", "dataType": "double", "sourceColumn": "fee_paid" },
          { "name": "total_payment", "dataType": "double", "sourceColumn": "total_payment" }
        ],
        "partitions": [
          {
            "name": "fct_daily_repayment",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"data/fct_daily_repayment.csv\"), [Delimiter=\",\", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"repayment_key\", Int64.Type}, {\"loan_key\", Int64.Type}, {\"payment_date_key\", Int64.Type}, {\"principal_paid\", type number}, {\"interest_paid\", type number}, {\"fee_paid\", type number}, {\"total_payment\", type number}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ]
      },
      {
        "name": "fct_loan_monthly_snapshot",
        "columns": [
          { "name": "snapshot_key", "dataType": "int64", "sourceColumn": "snapshot_key" },
          { "name": "snapshot_date_key", "dataType": "int64", "sourceColumn": "snapshot_date_key" },
          { "name": "loan_key", "dataType": "int64", "sourceColumn": "loan_key" },
          { "name": "customer_key", "dataType": "int64", "sourceColumn": "customer_key" },
          { "name": "product_key", "dataType": "int64", "sourceColumn": "product_key" },
          { "name": "outstanding_balance", "dataType": "double", "sourceColumn": "outstanding_balance" },
          { "name": "principal_due", "dataType": "double", "sourceColumn": "principal_due" },
          { "name": "interest_due", "dataType": "double", "sourceColumn": "interest_due" },
          { "name": "days_past_due", "dataType": "int64", "sourceColumn": "days_past_due" },
          { "name": "delinquency_bucket", "dataType": "string", "sourceColumn": "delinquency_bucket" },
          { "name": "is_impaired", "dataType": "int64", "sourceColumn": "is_impaired" },
          { "name": "ecl_stage", "dataType": "int64", "sourceColumn": "ecl_stage" }
        ],
        "measures": [
          {
            "name": "Total Outstanding Balance",
            "expression": "SUM(fct_loan_monthly_snapshot[outstanding_balance])",
            "formatString": "$#,##0.00"
          },
          {
            "name": "PAR 30 Balance",
            "expression": "CALCULATE(SUM(fct_loan_monthly_snapshot[outstanding_balance]), fct_loan_monthly_snapshot[days_past_due] >= 30)",
            "formatString": "$#,##0.00"
          },
          {
            "name": "PAR 30 Ratio",
            "expression": "DIVIDE([PAR 30 Balance], [Total Outstanding Balance], 0)",
            "formatString": "0.00%"
          },
          {
            "name": "PAR 60 Balance",
            "expression": "CALCULATE(SUM(fct_loan_monthly_snapshot[outstanding_balance]), fct_loan_monthly_snapshot[days_past_due] >= 60)",
            "formatString": "$#,##0.00"
          },
          {
            "name": "PAR 60 Ratio",
            "expression": "DIVIDE([PAR 60 Balance], [Total Outstanding Balance], 0)",
            "formatString": "0.00%"
          },
          {
            "name": "PAR 90 Balance",
            "expression": "CALCULATE(SUM(fct_loan_monthly_snapshot[outstanding_balance]), fct_loan_monthly_snapshot[days_past_due] >= 90)",
            "formatString": "$#,##0.00"
          },
          {
            "name": "PAR 90 Ratio",
            "expression": "DIVIDE([PAR 90 Balance], [Total Outstanding Balance], 0)",
            "formatString": "0.00%"
          },
          {
            "name": "NPL Balance",
            "expression": "CALCULATE(SUM(fct_loan_monthly_snapshot[outstanding_balance]), fct_loan_monthly_snapshot[is_impaired] = 1)",
            "formatString": "$#,##0.00"
          },
          {
            "name": "NPL Ratio",
            "expression": "DIVIDE([NPL Balance], [Total Outstanding Balance], 0)",
            "formatString": "0.00%"
          }
        ],
        "partitions": [
          {
            "name": "fct_loan_monthly_snapshot",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"data/fct_loan_monthly_snapshot.csv\"), [Delimiter=\",\", Columns=12, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"snapshot_key\", Int64.Type}, {\"snapshot_date_key\", Int64.Type}, {\"loan_key\", Int64.Type}, {\"customer_key\", Int64.Type}, {\"product_key\", Int64.Type}, {\"outstanding_balance\", type number}, {\"principal_due\", type number}, {\"interest_due\", type number}, {\"days_past_due\", Int64.Type}, {\"delinquency_bucket\", type text}, {\"is_impaired\", Int64.Type}, {\"ecl_stage\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "fct_snapshot_to_date",
        "fromTable": "fct_loan_monthly_snapshot",
        "fromColumn": "snapshot_date_key",
        "toTable": "dim_date",
        "toColumn": "date_key"
      },
      {
        "name": "fct_snapshot_to_customer",
        "fromTable": "fct_loan_monthly_snapshot",
        "fromColumn": "customer_key",
        "toTable": "dim_customer",
        "toColumn": "customer_key"
      },
      {
        "name": "fct_snapshot_to_product",
        "fromTable": "fct_loan_monthly_snapshot",
        "fromColumn": "product_key",
        "toTable": "dim_product",
        "toColumn": "product_key"
      },
      {
        "name": "fct_snapshot_to_loan",
        "fromTable": "fct_loan_monthly_snapshot",
        "fromColumn": "loan_key",
        "toTable": "dim_loan",
        "toColumn": "loan_key"
      },
      {
        "name": "fct_repayment_to_loan",
        "fromTable": "fct_daily_repayment",
        "fromColumn": "loan_key",
        "toTable": "dim_loan",
        "toColumn": "loan_key"
      },
      {
        "name": "fct_repayment_to_date",
        "fromTable": "fct_daily_repayment",
        "fromColumn": "payment_date_key",
        "toTable": "dim_date",
        "toColumn": "date_key"
      }
    ]
  }
}