table dim_loan
	lineageTag: cbd0cd5b-ec6e-4bd1-9441-56f0fcc9c64e

	column loan_id
		dataType: string
		lineageTag: f6c0d985-6aaa-4ed7-b96c-3d517f957004
		sourceColumn: loan_id

	column customer_id
		dataType: string
		lineageTag: ec62fb48-9c96-4450-b1bc-af3aedea043e
		sourceColumn: customer_id

	column product_id
		dataType: string
		lineageTag: bf9ad149-990f-4e7b-9aac-6e692e3cf9a9
		sourceColumn: product_id

	column origination_date
		dataType: dateTime
		lineageTag: cdb1f174-a03d-4f8a-9b80-da92fd4ef64a
		sourceColumn: origination_date

	column origination_year_month
		dataType: string
		lineageTag: 27a91683-8bdc-4dcc-8ad0-105efc90f678
		sourceColumn: origination_year_month

	column original_principal
		dataType: double
		lineageTag: ac0b2f77-b118-4068-a1b5-c51697acedbe
		sourceColumn: original_principal

	column annual_interest_rate
		dataType: double
		lineageTag: 482c9b8c-8659-4afd-a31d-42f0480cbd81
		sourceColumn: annual_interest_rate

	column term_months
		dataType: int64
		lineageTag: e5229d09-49ac-40d7-b907-720f931d823f
		sourceColumn: term_months

	column monthly_installment
		dataType: double
		lineageTag: 710744b3-22c1-4ca9-9e4c-adb253d989f4
		sourceColumn: monthly_installment

	column initial_credit_score
		dataType: int64
		lineageTag: 7bc6b283-6369-4a8e-a0f7-af4a406705b1
		sourceColumn: initial_credit_score

	column initial_risk_grade
		dataType: string
		lineageTag: 9cc8b310-9c3e-434c-b588-a968fa35f9ff
		sourceColumn: initial_risk_grade

	partition dim_loan_Partition = m
		mode: import
		source =
				let
				    CsvFile = File.Contents("C:/Users/Ary Palacios/Desktop/credit-risk-loan-analytics/data/dim_loan.csv"),
				    TableData = Csv.Document(CsvFile, [Delimiter=",", Columns=11, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    Headers = Table.PromoteHeaders(TableData, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Headers, {{"loan_id", type text}, {"customer_id", type text}, {"product_id", type text}, {"origination_date", type datetime}, {"origination_year_month", type text}, {"original_principal", type number}, {"annual_interest_rate", type number}, {"term_months", Int64.Type}, {"monthly_installment", type number}, {"initial_credit_score", Int64.Type}, {"initial_risk_grade", type text}}, "es-CL")
				in
				    Typed

