table fct_loan_monthly_snapshot
	lineageTag: e7ff5a3f-e483-4516-aede-f451be922fe4

	column snapshot_id
		dataType: string
		lineageTag: 73b55c4a-d5c9-4f47-8882-10f1f5812f3d
		summarizeBy: none
		sourceColumn: snapshot_id

		annotation SummarizationSetBy = Automatic

	column snapshot_date_id
		dataType: string
		lineageTag: 2c64d356-1a41-45b7-8a1a-109fb5f3067c
		summarizeBy: none
		sourceColumn: snapshot_date_id

		annotation SummarizationSetBy = Automatic

	column snapshot_date
		dataType: dateTime
		lineageTag: fe6cbd88-790e-4557-a670-0d791b07afa4
		summarizeBy: none
		sourceColumn: snapshot_date

		variation Variación
			isDefault
			relationship: bb5974e9-0288-4f20-b956-66b80bc6d8ac
			defaultHierarchy: LocalDateTable_8d3b01b8-7ca6-4fd5-8849-65cea5974ae2.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column loan_id
		dataType: string
		lineageTag: d025e2ee-81f0-4c60-b569-3d8750d30fb7
		summarizeBy: none
		sourceColumn: loan_id

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: string
		lineageTag: d7c9298a-5663-41f4-9b37-46b87930339b
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column product_id
		dataType: string
		lineageTag: 90d85b80-291f-42c8-9c7c-69e170735337
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column months_on_books
		dataType: int64
		lineageTag: 38528140-3b19-4283-8b46-c1c0e1aba9de
		summarizeBy: sum
		sourceColumn: months_on_books

		annotation SummarizationSetBy = Automatic

	column outstanding_principal
		dataType: double
		lineageTag: 155be869-cd65-4813-a604-3d1351dad522
		summarizeBy: sum
		sourceColumn: outstanding_principal

		annotation SummarizationSetBy = Automatic

	column accrued_interest
		dataType: double
		lineageTag: 0f6135f4-3561-4830-82bb-f9ba03cb23fe
		summarizeBy: sum
		sourceColumn: accrued_interest

		annotation SummarizationSetBy = Automatic

	column days_past_due
		dataType: int64
		lineageTag: 57568e00-94d8-4a59-b77a-bdb4bfbb7f96
		summarizeBy: sum
		sourceColumn: days_past_due

		annotation SummarizationSetBy = Automatic

	column delinquency_bucket
		dataType: string
		lineageTag: b97c68cf-1326-46c9-be89-ab0f410012e1
		summarizeBy: none
		sourceColumn: delinquency_bucket

		annotation SummarizationSetBy = Automatic

	column is_par30
		dataType: int64
		lineageTag: 2a92ad19-7792-4070-b781-dbe224bb3e9e
		summarizeBy: sum
		sourceColumn: is_par30

		annotation SummarizationSetBy = Automatic

	column is_par60
		dataType: int64
		lineageTag: 02f6ede3-0fdd-4923-b603-db288f963e9b
		summarizeBy: sum
		sourceColumn: is_par60

		annotation SummarizationSetBy = Automatic

	column is_par90
		dataType: int64
		lineageTag: c810ac60-815b-4dea-a4e9-5fd9b9147141
		summarizeBy: sum
		sourceColumn: is_par90

		annotation SummarizationSetBy = Automatic

	column is_npl
		dataType: int64
		lineageTag: d303016e-2544-4b18-bc2c-1541e1c56992
		summarizeBy: sum
		sourceColumn: is_npl

		annotation SummarizationSetBy = Automatic

	column loan_status
		dataType: string
		lineageTag: dea82863-c523-4608-ae0b-c82fe858b148
		summarizeBy: none
		sourceColumn: loan_status

		annotation SummarizationSetBy = Automatic

	partition fct_loan_monthly_snapshot_Partition = m
		mode: import
		source =
				let
				    CsvFile = File.Contents("C:/Users/Ary Palacios/Desktop/credit-risk-loan-analytics/data/fct_loan_monthly_snapshot.csv"),
				    TableData = Csv.Document(CsvFile, [Delimiter=",", Columns=16, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    Headers = Table.PromoteHeaders(TableData, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Headers, {{"snapshot_id", type text}, {"snapshot_date_id", type text}, {"snapshot_date", type datetime}, {"loan_id", type text}, {"customer_id", type text}, {"product_id", type text}, {"months_on_books", Int64.Type}, {"outstanding_principal", type number}, {"accrued_interest", type number}, {"days_past_due", Int64.Type}, {"delinquency_bucket", type text}, {"is_par30", Int64.Type}, {"is_par60", Int64.Type}, {"is_par90", Int64.Type}, {"is_npl", Int64.Type}, {"loan_status", type text}}, "es-CL")
				in
				    Typed

