table dim_customer
lineageTag: a1b2c3d4-cust-0003

column customer_id
dataType: int64
formatString: 0
lineageTag: a1b2c3d4-cust-col1
summarizeBy: none
sourceColumn: customer_id

column customer_name
dataType: string
lineageTag: a1b2c3d4-cust-col2
summarizeBy: none
sourceColumn: customer_name

column age
dataType: int64
formatString: 0
lineageTag: a1b2c3d4-cust-col3
summarizeBy: none
sourceColumn: age

column monthly_income
dataType: double
formatString: \$#,0.00;(\$#,0.00);\.00
lineageTag: a1b2c3d4-cust-col4
summarizeBy: none
sourceColumn: monthly_income

column credit_score
dataType: int64
formatString: 0
lineageTag: a1b2c3d4-cust-col5
summarizeBy: none
sourceColumn: credit_score

column credit_score_band
dataType: string
lineageTag: a1b2c3d4-cust-col6
summarizeBy: none
sourceColumn: credit_score_band

column employment_type
dataType: string
lineageTag: a1b2c3d4-cust-col7
summarizeBy: none
sourceColumn: employment_type

column region
dataType: string
lineageTag: a1b2c3d4-cust-col8
summarizeBy: none
sourceColumn: region

partition dim_customer = m
mode: import
source =
let
Source = Csv.Document(File.Contents("data/dim_customer.csv"),[Delimiter=",", Columns=8, Encoding=65001, QuoteStyle=QuoteStyle.None]),
#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"customer_id", Int64.Type}, {"customer_name", type text}, {"age", Int64.Type}, {"monthly_income", type number}, {"credit_score", Int64.Type}, {"credit_score_band", type text}, {"employment_type", type text}, {"region", type text}})
in
#"Changed Type"