table dim_loan
lineageTag: a1b2c3d4-loan-0004

column loan_id
dataType: int64
formatString: 0
lineageTag: a1b2c3d4-loan-col1
summarizeBy: none
sourceColumn: loan_id

column customer_id
dataType: int64
formatString: 0
lineageTag: a1b2c3d4-loan-col2
summarizeBy: none
sourceColumn: customer_id

column product_id
dataType: int64
formatString: 0
lineageTag: a1b2c3d4-loan-col3
summarizeBy: none
sourceColumn: product_id

column origination_date
dataType: dateTime
formatString: yyyy-mm-dd
lineageTag: a1b2c3d4-loan-col4
summarizeBy: none
sourceColumn: origination_date

column origination_year_month
dataType: string
lineageTag: a1b2c3d4-loan-col5
summarizeBy: none
sourceColumn: origination_year_month

column original_principal
dataType: double
formatString: \$#,0.00;(\$#,0.00);\.00
lineageTag: a1b2c3d4-loan-col6
summarizeBy: sum
sourceColumn: original_principal

column annual_interest_rate
dataType: double
formatString: 0.00%
lineageTag: a1b2c3d4-loan-col7
summarizeBy: none
sourceColumn: annual_interest_rate

column term_months
dataType: int64
formatString: 0
lineageTag: a1b2c3d4-loan-col8
summarizeBy: none
sourceColumn: term_months

column monthly_installment
dataType: double
formatString: \$#,0.00;(\$#,0.00);\.00
lineageTag: a1b2c3d4-loan-col9
summarizeBy: none
sourceColumn: monthly_installment

column initial_credit_score
dataType: int64
formatString: 0
lineageTag: a1b2c3d4-loan-col10
summarizeBy: none
sourceColumn: initial_credit_score

column initial_risk_grade
dataType: string
lineageTag: a1b2c3d4-loan-col11
summarizeBy: none
sourceColumn: initial_risk_grade

partition dim_loan = m
mode: import
source =
let
Source = Csv.Document(File.Contents("data/dim_loan.csv"),[Delimiter=",", Columns=11, Encoding=65001, QuoteStyle=QuoteStyle.None]),
#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"loan_id", Int64.Type}, {"customer_id", Int64.Type}, {"product_id", Int64.Type}, {"origination_date", type date}, {"origination_year_month", type text}, {"original_principal", type number}, {"annual_interest_rate", type number}, {"term_months", Int64.Type}, {"monthly_installment", type number}, {"initial_credit_score", Int64.Type}, {"initial_risk_grade", type text}})
in
#"Changed Type"