table fct_daily_repayment
lineageTag: a1b2c3d4-fact-0005

measure 'Total Collections' = SUM(fct_daily_repayment[total_paid])
formatString: \$#,0.00;(\$#,0.00);\.00
lineageTag: m-col-001

measure 'Principal Collected' = SUM(fct_daily_repayment[principal_paid])
formatString: \$#,0.00;(\$#,0.00);\.00
lineageTag: m-col-002

measure 'Interest Income Collected' = SUM(fct_daily_repayment[interest_paid])
formatString: \$#,0.00;(\$#,0.00);\.00
lineageTag: m-col-003

column repayment_id
dataType: string
lineageTag: a1b2c3d4-rep-col1
summarizeBy: none
sourceColumn: repayment_id

column payment_date_id
dataType: int64
formatString: 0
lineageTag: a1b2c3d4-rep-col2
summarizeBy: none
sourceColumn: payment_date_id

column payment_date
dataType: dateTime
formatString: yyyy-mm-dd
lineageTag: a1b2c3d4-rep-col3
summarizeBy: none
sourceColumn: payment_date

column loan_id
dataType: int64
formatString: 0
lineageTag: a1b2c3d4-rep-col4
summarizeBy: none
sourceColumn: loan_id

column principal_paid
dataType: double
formatString: \$#,0.00;(\$#,0.00);\.00
lineageTag: a1b2c3d4-rep-col5
summarizeBy: sum
sourceColumn: principal_paid

column interest_paid
dataType: double
formatString: \$#,0.00;(\$#,0.00);\.00
lineageTag: a1b2c3d4-rep-col6
summarizeBy: sum
sourceColumn: interest_paid

column fees_paid
dataType: double
formatString: \$#,0.00;(\$#,0.00);\.00
lineageTag: a1b2c3d4-rep-col7
summarizeBy: sum
sourceColumn: fees_paid

column total_paid
dataType: double
formatString: \$#,0.00;(\$#,0.00);\.00
lineageTag: a1b2c3d4-rep-col8
summarizeBy: sum
sourceColumn: total_paid

column days_past_due_at_payment
dataType: int64
formatString: 0
lineageTag: a1b2c3d4-rep-col9
summarizeBy: none
sourceColumn: days_past_due_at_payment

partition fct_daily_repayment = m
mode: import
source =
let
Source = Csv.Document(File.Contents("data/fct_daily_repayment.csv"),[Delimiter=",", Columns=9, Encoding=65001, QuoteStyle=QuoteStyle.None]),
#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"repayment_id", type text}, {"payment_date_id", Int64.Type}, {"payment_date", type date}, {"loan_id", Int64.Type}, {"principal_paid", type number}, {"interest_paid", type number}, {"fees_paid", type number}, {"total_paid", type number}, {"days_past_due_at_payment", Int64.Type}})
in
#"Changed Type"